### ISSUE TITLE
May I request to change Google Analytics Tracking ID?

### ISSUE THREAD

**Issue by hanmilLee** [chusight/o-id#3]
Hello~

May I request to change Google Analytics Tracking ID?

Your blog is also counting in my GA.
Please note that this issue will not occur in the future if you specify it as a Vercel environment variable as shown below.

https://github.com/hanmilLee/nextjs-notion-starter-kit/commit/9c6e083ed15355c7c0ecd2a8770b4b66f99dff83
<img width="1009" alt="2022-05-12_23-54-17" src="https://user-images.githubusercontent.com/47099020/168104665-9e3be379-2ce2-45b9-9ab8-ae4ac6d79db1.png">

**Comment by chusight** [comment]
수정했습니다 죄송합니다
